FROM  python:bullseye

RUN apt-get update
RUN apt-get -y install python3-dev python3-setuptools build-essential python3-pip
RUN apt-get -y install wget 
RUN wget https://bootstrap.pypa.io/get-pip.py
RUN python3 get-pip.py

RUN mkdir /opt/bos-bacnet-server
COPY * /opt/bos-bacnet-server/

WORKDIR /opt/bos-bacnet-server
RUN python3 -m pip install wheel
RUN python3 -m pip install -r requirements.txt

EXPOSE 47808

CMD python3 bos-bacnet-server.py


